name: material_duration_picker
description: "A duration picker using the material design of the time picker."
version: 0.1.1
resolution: workspace
repository: https://github.com/Oberhauser-Dev/dart_packages/tree/main/packages/material_duration_picker

environment:
  sdk: ^3.6.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
